version: "3.8"
services:
    www:
       build: docker/php
       container_name: my_project_symfony
      ports:
        - 8080:80
      networks:
        - my_project_symfony
      db:
        image: mysql
        container_name: my_project_mysql
        volumes:
           - ./var/dv_data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD : 'yes'
        networks:
            - my_project_symfony
        phpmyadmin:
          image : phpmyadmin
          container_name: my_project_phpmyadmin
          ports:
            - 8780:80
      networks:
        - my_project_symfony